# Generated by Django 5.0.1 on 2024-02-03 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividadeconomica',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', default='N/A', max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Actividad económica',
                'verbose_name_plural': 'Actividades económicas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', default='001', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', default='001', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoContribuyente',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', default='001', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de contribuyente',
                'verbose_name_plural': 'Tipos de contribuyente',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoIdentificacion',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Numero', max_length=50, null=True, verbose_name='Número de documento')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idMunicipio', models.CharField(db_column='Id', default='001', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('codigo', models.CharField(db_column='Codigo', default='001', max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=200, verbose_name='Nombre')),
                ('departamento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dte.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('razonsocial', models.CharField(blank=True, db_column='RazonSocial', max_length=100, null=True, verbose_name='Razón social')),
                ('nombreComercial', models.CharField(blank=True, db_column='NombreComercial', default='', max_length=50, null=True, verbose_name='Nombre comercial')),
                ('nit', models.CharField(blank=True, db_column='NIT', max_length=20, null=True, verbose_name='NIT')),
                ('nrc', models.CharField(blank=True, db_column='NRC', max_length=10, null=True, verbose_name='NRC')),
                ('dui', models.CharField(blank=True, db_column='DUI', max_length=10, null=True, verbose_name='DUI')),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True, verbose_name='Teléfono')),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=200, null=True, verbose_name='Correo')),
                ('direccionComplemento', models.CharField(blank=True, db_column='Direccion', max_length=200, null=True)),
                ('actividadEconomica', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.actividadeconomica')),
                ('departamento', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.departamento')),
                ('municipio', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.municipio')),
                ('pais', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.pais')),
                ('TipoContribuyente', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontribuyente')),
            ],
            options={
                'ordering': ('razonsocial',),
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('razonsocial', models.CharField(blank=True, db_column='RazonSocial', max_length=100, null=True, verbose_name='Razón social')),
                ('nombreComercial', models.CharField(blank=True, db_column='NombreComercial', default='', max_length=50, null=True, verbose_name='Nombre comercial')),
                ('numeroDocumento', models.CharField(blank=True, db_column='numeroDocumento', max_length=50, null=True, verbose_name='Número de documento')),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True, verbose_name='Teléfono')),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=200, null=True, verbose_name='Correo')),
                ('direccionComplemento', models.CharField(blank=True, db_column='Direccion', max_length=200, null=True)),
                ('actividadEconomica', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.actividadeconomica')),
                ('departamento', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.departamento')),
                ('empresa', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
                ('municipio', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.municipio')),
                ('pais', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.pais')),
                ('TipoContribuyente', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontribuyente')),
                ('tipoDocumentoCliente', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumentoidentificacion', verbose_name='Tipo de documento')),
            ],
            options={
                'ordering': ('razonsocial',),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('razonsocial', models.CharField(blank=True, db_column='RazonSocial', max_length=100, null=True, verbose_name='Razón social')),
                ('nombreComercial', models.CharField(blank=True, db_column='NombreComercial', default='', max_length=50, null=True, verbose_name='Nombre comercial')),
                ('numeroDocumento', models.CharField(blank=True, db_column='numeroDocumento', max_length=50, null=True, verbose_name='Número de documento')),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True, verbose_name='Teléfono')),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=200, null=True, verbose_name='Correo')),
                ('direccionComplemento', models.CharField(blank=True, db_column='Direccion', max_length=200, null=True)),
                ('actividadEconomica', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.actividadeconomica')),
                ('departamento', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.departamento')),
                ('empresa', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
                ('municipio', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.municipio')),
                ('pais', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.pais')),
                ('TipoContribuyente', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontribuyente')),
                ('tipoDocumentoCliente', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumentoidentificacion', verbose_name='Tipo de documento')),
            ],
            options={
                'ordering': ('razonsocial',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
