# Generated by Django 5.0.1 on 2024-02-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbienteDestino',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Ambiente de destino',
                'verbose_name_plural': 'Ambientes de destino',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='UrlSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_firmado', models.URLField(db_column='URLFirmado', max_length=100, verbose_name='Url para firmar DTE')),
                ('url_auth_prueba', models.URLField(db_column='URLAuthPruebas', max_length=100, verbose_name='URL autenticación pruebas')),
                ('url_auth_produccion', models.URLField(db_column='URLAuthProduccion', max_length=100, verbose_name='URL autenticación producción')),
                ('url_envio_prueba', models.URLField(db_column='URLEnvioPruebas', max_length=100, verbose_name='URL para envío DTE pruebas')),
                ('url_envio_produccion', models.URLField(db_column='URLEnvioProduccion', max_length=100, verbose_name='URL para envío DTE producción')),
                ('url_anulacion_prueba', models.URLField(db_column='URLAnulacionPruebas', max_length=100, verbose_name='URL para envío DTE pruebas')),
                ('url_anulacion_produccion', models.URLField(db_column='URLAnulacionProduccion', max_length=100, verbose_name='URL para envío DTE producción')),
                ('url_contingencia_prueba', models.URLField(db_column='URLContingenciaPruebas', max_length=100, verbose_name='URL para envío DTE pruebas')),
                ('url_contingencia_produccion', models.URLField(db_column='URLContingenciaProduccion', max_length=100, verbose_name='URL para envío DTE producción')),
                ('url_almacen_archivos', models.CharField(db_column='URLAlmacenArchivos', default='', max_length=100, verbose_name='URL para almacenar archivos')),
                ('url_absoluta_static', models.CharField(db_column='URLAbsolutaStatic', default='', max_length=100, verbose_name='URL absoluta carpeta static')),
            ],
            options={
                'verbose_name': 'URL del sistema',
                'verbose_name_plural': 'URLs del sistema',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='ambiente',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.ambientedestino'),
        ),
        migrations.CreateModel(
            name='ConfigSeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(db_column='Usuario', max_length=50, verbose_name='Usuario')),
                ('passwordAPI', models.CharField(db_column='PasswordAPI', default='', max_length=50, verbose_name='Clave acceso API test (generar token MH)')),
                ('passwordPri', models.CharField(db_column='PasswordPri', default='', max_length=50, verbose_name='Clave privada test')),
                ('token', models.TextField(db_column='Token', default='', max_length=500, verbose_name='Token test')),
                ('usuario_correo', models.EmailField(db_column='UsuarioCorreo', default='none@usuario.com', max_length=500, verbose_name='Usuario de correo')),
                ('clave_correo', models.CharField(db_column='ClaveCorreo', default='', max_length=500, verbose_name='Clave de correo')),
                ('smtp', models.CharField(db_column='SMTP', default='', max_length=500, verbose_name='Servidor SMTP')),
                ('puerto_smtp', models.IntegerField(db_column='PuertoSMTP', default=587, verbose_name='Puerto SMTP')),
                ('EnableSsl', models.BooleanField(db_column='EnableSsl', default=True, verbose_name='Utiliza SSL')),
                ('empresa', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de seguridad',
                'verbose_name_plural': 'Configuraciones de seguridad',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', default='', max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('cantidadMinima', models.DecimalField(blank=True, db_column='CantidadMinima', decimal_places=2, max_digits=18, null=True, verbose_name='Cantidad mínima')),
                ('empresa', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
            ],
        ),
    ]
