# Generated by Django 5.0.1 on 2024-02-03 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0002_ambientedestino_urlsistema_empresa_ambiente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionOperacion',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Condición de la operación',
                'verbose_name_plural': 'Condiciones de la operaciones',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='DomicilioFiscal',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Domicilio fiscal',
                'verbose_name_plural': 'Domicilios fiscales',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='EstadoDTE',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Estado DTE',
                'verbose_name_plural': 'Estados de DTE',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Forma de pago',
                'verbose_name_plural': 'Formas de pago',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ImpuestoAdValorem',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Impuesto AD Valorem',
                'verbose_name_plural': 'Impuestos AD Valorem',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Intcoterm',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Intcoterm',
                'verbose_name_plural': 'Intcoterms',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ModeloFacturacion',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Modelo de facturación',
                'verbose_name_plural': 'Modelos de facturación',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
                ('prefijo', models.CharField(blank=True, db_column='Prefijo', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='OtroDocumentoAsociado',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Otro documento asociado',
                'verbose_name_plural': 'Otros documentos asociados',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Plazo',
                'verbose_name_plural': 'Plazos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='RecintoFiscal',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Recinto fiscal',
                'verbose_name_plural': 'Recintos fiscales',
                'db_table': 'dte_tblRecintoFiscal',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Régimen',
                'verbose_name_plural': 'Regimenes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='RetencionIVAMH',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Retención IVA MH',
                'verbose_name_plural': 'Retenciones IVA MH',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoContingencia',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de contingencia',
                'verbose_name_plural': 'Tipos de contingencia',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
                ('nombre_corto', models.CharField(blank=True, db_column='NombreCorto', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoContingencia',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de documento en contingencia',
                'verbose_name_plural': 'Tipos de documento en contingencia',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoDonacion',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de donación',
                'verbose_name_plural': 'Tipos de donación',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de establecimiento',
                'verbose_name_plural': 'Tipos de establecimiento',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoGeneracionDocumento',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de generación del documento',
                'verbose_name_plural': 'Tipos de generación de los documentos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoInvalidacion',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de invalidación',
                'verbose_name_plural': 'Tipos de invalidación',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de ítem',
                'verbose_name_plural': 'Tipos de ítem',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de persona',
                'verbose_name_plural': 'Tips de persona',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoServicioMedico',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de servicio médico',
                'verbose_name_plural': 'Tipos de servicios médicos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoTransmision',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de transmisión',
                'verbose_name_plural': 'Tipos de transmisión',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TituloRemision',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Título a que se remiten los bienes',
                'verbose_name_plural': 'Títulos a que se remiten los bienes',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de transporte',
                'verbose_name_plural': 'Tipos de transporte',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TributoCuerpo',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tributo cuerpo',
                'verbose_name_plural': 'Tributos cuerpo',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TributoResumen',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Tributo resumen',
                'verbose_name_plural': 'Tributos resumen',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ('nombre',),
            },
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='TipoContribuyente',
            new_name='tipoContribuyente',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='TipoContribuyente',
            new_name='tipoContribuyente',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='TipoContribuyente',
            new_name='tipoContribuyente',
        ),
        migrations.CreateModel(
            name='ControlDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroactual', models.IntegerField(db_column='NumeroActual', default=0, verbose_name='Número actual')),
                ('empresa', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento')),
            ],
            options={
                'verbose_name': 'Control documento',
                'verbose_name_plural': 'Control documentos',
                'ordering': ('empresa',),
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoPersona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipopersona'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipoPersona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipopersona'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipoPersona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipopersona'),
        ),
    ]
