# Generated by Django 5.0.1 on 2024-02-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0003_condicionoperacion_domiciliofiscal_estadodte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.CharField(db_column='departamento_id', max_length=100),
        ),
    ]
