# Generated by Django 5.0.1 on 2024-02-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0006_alter_tipodocumentoidentificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recintofiscal',
            table=None,
        ),
    ]
