# Generated by Django 5.0.1 on 2024-02-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0007_alter_recintofiscal_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intcoterm',
            new_name='Incoterm',
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={'ordering': ('codigo',), 'verbose_name': 'Tipo de transporte', 'verbose_name_plural': 'Tipos de transporte'},
        ),
    ]
