# Generated by Django 5.0.1 on 2024-02-03 12:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0008_rename_intcoterm_incoterm_alter_transporte_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ('codigo',), 'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documento'},
        ),
        migrations.CreateModel(
            name='DTECliente',
            fields=[
                ('selloRecepcion', models.CharField(blank=True, db_column='SelloRecepcion', default='', max_length=100, null=True, verbose_name='Sello de recepción')),
                ('version', models.IntegerField(db_column='Version', default=3, verbose_name='Versión JSON')),
                ('numeroControl', models.CharField(blank=True, db_column='NumeroControl', default='', max_length=31, null=True, verbose_name='Número de control')),
                ('codigoGeneracion', models.CharField(db_column='CodigoGeneracion', default='', max_length=36, primary_key=True, serialize=False, verbose_name='Código de generación')),
                ('motivoContin', models.CharField(blank=True, db_column='MotivoContingncia', default='', max_length=255, null=True, verbose_name='Motivo de contingencia')),
                ('fecEmi', models.DateTimeField(db_column='FechaEmision', default=datetime.datetime.now, verbose_name='Fecha de emisión')),
                ('totalNoSuj', models.DecimalField(blank=True, db_column='TotalNoSujetas', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total no sujetas')),
                ('totalExenta', models.DecimalField(blank=True, db_column='TotalExentas', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total exentas')),
                ('totalGravada', models.DecimalField(blank=True, db_column='TotalGravada', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total gravadas')),
                ('subTotalVentas', models.DecimalField(blank=True, db_column='SubTotalVentas', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Sub-total ventas')),
                ('descuNoSuj', models.DecimalField(blank=True, db_column='DescuentoNoSujetas', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Descuento no sujetas')),
                ('descuExenta', models.DecimalField(blank=True, db_column='DescuentoExenta', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Descuento exentas')),
                ('descuGravada', models.DecimalField(blank=True, db_column='DescuentoGravada', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Descuento gravadas')),
                ('porcentajeDescuento', models.DecimalField(blank=True, db_column='PorcentajeDescuento', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Porcentaje descuento')),
                ('totalDescu', models.DecimalField(blank=True, db_column='TotalDescuento', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total descuento')),
                ('subTotal', models.DecimalField(blank=True, db_column='SubTotal', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Sub total')),
                ('ivaPerci1', models.DecimalField(blank=True, db_column='IVAPercibido', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='IVA rercibido')),
                ('ivaRete1', models.DecimalField(blank=True, db_column='IVARetenido', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='IVA retenido')),
                ('reteRenta', models.DecimalField(blank=True, db_column='RetencionRenta', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Retención de renta')),
                ('montoTotalOperacion', models.DecimalField(blank=True, db_column='MontoTotalOperacion', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Monto total de operación')),
                ('totalNoGravado', models.DecimalField(blank=True, db_column='TotalNoGravado', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total no gravado')),
                ('totalPagar', models.DecimalField(blank=True, db_column='TotalAPagar', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total a pagar')),
                ('totalLetras', models.CharField(blank=True, db_column='TotalEnLetras', default='', max_length=200, null=True, verbose_name='Total en letras')),
                ('saldoFavor', models.DecimalField(blank=True, db_column='SaldoAFavor', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Saldo a favor')),
                ('pagos', models.IntegerField(blank=True, db_column='Pagos', default=1)),
                ('numPagoElectronico', models.IntegerField(blank=True, db_column='NumeroPagoElectronico', null=True, verbose_name='Número de pago electrónico')),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=3000, null=True, verbose_name='Observaciones')),
                ('placaVehiculo', models.CharField(blank=True, db_column='PlacaVehiculo', max_length=10, null=True, verbose_name='Placa del vehículo')),
                ('docfirmado', models.TextField(blank=True, db_column='DocFirmado', null=True, verbose_name='Documento firmado')),
                ('ambiente', models.ForeignKey(db_column='Ambiente', default='00', on_delete=django.db.models.deletion.CASCADE, to='dte.ambientedestino', verbose_name='Ambiente de trabajo')),
                ('condicionOperacion', models.ForeignKey(db_column='CondicionOperacion', default='2', on_delete=django.db.models.deletion.CASCADE, to='dte.condicionoperacion', verbose_name='Condición de la operación')),
                ('emisor', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
                ('estadoDte', models.ForeignKey(blank=True, default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.estadodte', verbose_name='Estado del DTE')),
                ('receptor', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.cliente')),
                ('tipoContingencia', models.ForeignKey(blank=True, db_column='TipoContingencia', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontingencia', verbose_name='Tipo de contingencia')),
                ('tipoDte', models.ForeignKey(db_column='TipoDTE', default='', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo DTE')),
                ('tipoModelo', models.ForeignKey(db_column='TipoModelo', default='1', on_delete=django.db.models.deletion.CASCADE, to='dte.modelofacturacion', verbose_name='Tipo de modelo')),
                ('tipoMoneda', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.moneda')),
                ('tipoTransmision', models.ForeignKey(db_column='TipoTransmision', default='1', on_delete=django.db.models.deletion.CASCADE, to='dte.tipotransmision', verbose_name='Tipo de transmisión')),
            ],
            options={
                'verbose_name': 'DTE de cliente',
                'verbose_name_plural': "DTE's de clientes",
                'ordering': ('-fecEmi',),
            },
        ),
    ]
