# Generated by Django 5.0.1 on 2024-02-03 12:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0009_alter_tipodocumento_options_dtecliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTEClienteDetalle',
            fields=[
                ('codigoDetalle', models.CharField(db_column='CodigoDetalle', default='', max_length=36, primary_key=True, serialize=False)),
                ('numeroDocumento', models.CharField(blank=True, db_column='numeroDocumento', default='', max_length=36, null=True, verbose_name='Número de documento')),
                ('fechaEmision', models.DateTimeField(db_column='FechaEmision', default=datetime.datetime.now, verbose_name='Fecha de emisión')),
                ('cantidad', models.DecimalField(blank=True, db_column='Cantidad', decimal_places=3, default=1, max_digits=11, verbose_name='Cantidad')),
                ('codigo', models.CharField(blank=True, db_column='Codigo', default='', max_length=25, verbose_name='Codigo')),
                ('descripcion', models.CharField(db_column='Descripcion', default='', max_length=1000, verbose_name='Descripción')),
                ('precioUni', models.DecimalField(db_column='PrecioUnitario', decimal_places=2, default=0, max_digits=11, verbose_name='Precio unitario')),
                ('montoDescu', models.DecimalField(db_column='MontoDescuento', decimal_places=2, default=0, max_digits=11, verbose_name='Monto de descuento')),
                ('ventaNoSuj', models.DecimalField(db_column='VentaNoSujeta', decimal_places=2, default=0, max_digits=11, verbose_name='Venta no sujeta')),
                ('ventaExenta', models.DecimalField(db_column='VentaExenta', decimal_places=2, default=0, max_digits=11, verbose_name='Venta exenta')),
                ('ventaGravada', models.DecimalField(db_column='VentaGravada', decimal_places=2, default=0, max_digits=11, verbose_name='Venta gravada')),
                ('exportaciones', models.DecimalField(db_column='Exportaciones', decimal_places=2, default=0, max_digits=11)),
                ('compra', models.DecimalField(db_column='Compra', decimal_places=2, default=0, max_digits=11)),
                ('psv', models.DecimalField(db_column='PSV', decimal_places=2, default=0, max_digits=11, verbose_name='Precio sugerido de venta')),
                ('noGravado', models.DecimalField(db_column='NoGravado', decimal_places=2, default=0, max_digits=11, verbose_name='No gravado')),
                ('ivaItem', models.DecimalField(db_column='IVAItem', decimal_places=2, default=0, max_digits=11, verbose_name='IVA item')),
                ('montoSujetoGrav', models.DecimalField(db_column='MontoSujetoGravado', decimal_places=2, default=0, max_digits=11, verbose_name='Monto sujeto gravado')),
                ('codigoRetencionMH', models.DecimalField(db_column='CodigoRetencionMH', decimal_places=2, default=0, max_digits=11, verbose_name='Código retención MH')),
                ('ivaRetenido', models.DecimalField(db_column='IVARetenido', decimal_places=2, default=0, max_digits=11, verbose_name='IVA retenido')),
                ('periodoLiquidacionFechaInicio', models.DateTimeField(db_column='PeriodoLiquidacionFechaInicio', default=datetime.datetime.now, verbose_name='Inicio período liquidación')),
                ('periodoLiquidacionFechaFin', models.DateTimeField(db_column='PeriodoLiquidacionFechaFin', default=datetime.datetime.now, verbose_name='Fin período liquidación')),
                ('codLiquidacion', models.CharField(db_column='CodigoLiquidacion', default='', max_length=30, verbose_name='Código de liquidación')),
                ('cantidadDoc', models.IntegerField(db_column='CantidadDocumentos', default=0, verbose_name='Cantidad documentos')),
                ('valorOperaciones', models.DecimalField(db_column='ValorOperaciones', decimal_places=2, default=0, max_digits=11, verbose_name='Valor operaciones')),
                ('montoSinPercepcion', models.DecimalField(db_column='MontoSinPercepcion', decimal_places=2, default=0, max_digits=11, verbose_name='Monto sin percepción')),
                ('descripcionPercepcion', models.CharField(db_column='DescripcionPercepcion', default='', max_length=100, verbose_name='Descripción percepción')),
                ('obsitem', models.CharField(db_column='ObsItem', max_length=3000, null=True, verbose_name='Observaciones')),
                ('observaciones', models.CharField(db_column='Observaciones', max_length=200, null=True, verbose_name='Observaciones')),
                ('complemento1', models.CharField(blank=True, db_column='Complemento1', default='', max_length=3000, null=True, verbose_name='Complemento 1')),
                ('complemento2', models.CharField(blank=True, db_column='Complemento2', default='', max_length=3000, null=True, verbose_name='Complemento 2')),
                ('subTotal', models.DecimalField(db_column='SubTotal', decimal_places=2, default=0, max_digits=11, verbose_name='Sub-total')),
                ('iva', models.DecimalField(db_column='IVA', decimal_places=2, default=0, max_digits=11)),
                ('montoSujetoPercepcion', models.DecimalField(db_column='MontoSujetoPercepcion', decimal_places=2, default=0, max_digits=11, verbose_name='Monto sujeto percepción')),
                ('ivaPercibido', models.DecimalField(db_column='IVAPercibido', decimal_places=2, default=0, max_digits=11, verbose_name='IVA Percibido')),
                ('comision', models.DecimalField(db_column='Comision', decimal_places=2, default=0, max_digits=11, verbose_name='Comisión')),
                ('porcentComision', models.DecimalField(db_column='PorcentajeComision', decimal_places=2, default=0, max_digits=11, verbose_name='Porcentaje comisión')),
                ('IVAComision', models.DecimalField(db_column='IVAComision', decimal_places=2, default=0, max_digits=11, verbose_name='IVA comisión')),
                ('liquidoApagar', models.DecimalField(db_column='LiquidoAPagar', decimal_places=2, default=0, max_digits=11, verbose_name='Líquido a pagar')),
                ('totalLetras', models.CharField(db_column='TotalLetras', default='', max_length=200, verbose_name='Total en letras')),
                ('dte', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dte.dtecliente')),
                ('tipoDoc', models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo de documento')),
                ('tipoGeneracion', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dte.tipogeneraciondocumento', verbose_name='Tipo de generación')),
                ('tipoItem', models.ForeignKey(db_column='tipoItem_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='dte.tipoitem', verbose_name='Tipo de ítem')),
                ('tributos', models.ForeignKey(blank=True, db_column='tributos_id', default='20', on_delete=django.db.models.deletion.CASCADE, to='dte.tributoresumen')),
                ('uniMedida', models.ForeignKey(db_column='uniMedida_id', default='34', on_delete=django.db.models.deletion.CASCADE, to='dte.unidadmedida', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'DTE cliente detalle',
                'verbose_name_plural': "DTE's cliente detalles",
            },
        ),
    ]
