# Generated by Django 5.0.1 on 2024-02-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0010_dteclientedetalle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
