# Generated by Django 5.0.1 on 2024-02-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0015_alter_dteclientedetalle_codigodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='codigoDetalle',
            field=models.CharField(db_column='CodigoDetalle', default='B1B1614F-F5C9-40B9-B16C-DE03B60FE7BA', max_length=36, primary_key=True, serialize=False),
        ),
    ]
