# Generated by Django 5.0.1 on 2024-02-13 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0016_alter_dteclientedetalle_codigodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='codigoDetalle',
            field=models.CharField(db_column='CodigoDetalle', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='observaciones',
            field=models.CharField(db_column='Observaciones', default='', max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='obsitem',
            field=models.CharField(db_column='ObsItem', default='', max_length=3000, null=True, verbose_name='Observaciones'),
        ),
        migrations.CreateModel(
            name='DtesEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo de documento autorizado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Dte autorizado por empresa',
                'verbose_name_plural': "Dte's autorizados por empresa",
            },
        ),
    ]
