# Generated by Django 5.0.1 on 2024-02-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0017_alter_dteclientedetalle_codigodetalle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtesempresa',
            options={'ordering': ('dte',), 'verbose_name': 'Dte autorizado por empresa', 'verbose_name_plural': "Dte's autorizados por empresa"},
        ),
        migrations.AddField(
            model_name='dtecliente',
            name='estadoPago',
            field=models.BooleanField(blank=True, db_column='estadoPago', default=True, verbose_name='Estado pago'),
        ),
    ]
