# Generated by Django 5.0.1 on 2024-02-18 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0018_alter_dtesempresa_options_dtecliente_estadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtecliente',
            name='fechaPago',
            field=models.DateTimeField(db_column='fechaPago', default=datetime.datetime.now, verbose_name='Fecha de pago'),
        ),
    ]
