# Generated by Django 5.0.1 on 2024-02-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0019_dtecliente_fechapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de pago',
                'verbose_name_plural': 'Estados de pago',
                'ordering': ('codigo',),
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='actividadEconomica',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.actividadeconomica', verbose_name='Actividad económica'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(db_column='Correo', default='cliente@cliente.com', max_length=200, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='departamento',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccionComplemento',
            field=models.CharField(blank=True, db_column='Direccion', default='', max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeroDocumento',
            field=models.CharField(db_column='numeroDocumento', default='', max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razonsocial',
            field=models.CharField(db_column='RazonSocial', default='', max_length=100, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(db_column='Telefono', default='', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoContribuyente',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontribuyente', verbose_name='Tipo de contribuyente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoPersona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipopersona', verbose_name='Tipo de persona'),
        ),
    ]
