# Generated by Django 5.0.1 on 2024-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0020_estadopago_alter_cliente_actividadeconomica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtecliente',
            name='estadoPago',
            field=models.BooleanField(blank=True, db_column='estadoPago', default=True, verbose_name='Pagado'),
        ),
    ]
