# Generated by Django 5.0.1 on 2024-02-25 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0021_alter_dtecliente_estadopago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default='A4BCBC83-4C59-4A3F-9C25-807D83AD0837', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa'),
        ),
        migrations.AlterField(
            model_name='configseg',
            name='empresa',
            field=models.ForeignKey(default='A4BCBC83-4C59-4A3F-9C25-807D83AD0837', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa'),
        ),
        migrations.AlterField(
            model_name='controldocumento',
            name='empresa',
            field=models.ForeignKey(default='A4BCBC83-4C59-4A3F-9C25-807D83AD0837', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='emisor',
            field=models.ForeignKey(default='A4BCBC83-4C59-4A3F-9C25-807D83AD0837', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(default='A4BCBC83-4C59-4A3F-9C25-807D83AD0837', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(default='A4BCBC83-4C59-4A3F-9C25-807D83AD0837', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa'),
        ),
    ]
