# Generated by Django 5.0.1 on 2024-02-25 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0022_alter_cliente_empresa_alter_configseg_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='codigoDetalle',
            field=models.CharField(blank=True, db_column='CodigoDetalle', default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
    ]
