# Generated by Django 5.0.1 on 2024-02-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0023_alter_dteclientedetalle_codigodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigoEstablecimiento',
            field=models.CharField(blank=True, db_column='codigoEstablecimiento', default='', max_length=4, null=True, verbose_name='Código de establecimiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigoPuntoVenta',
            field=models.CharField(blank=True, db_column='codigoPuntoVenta', default='', max_length=4, null=True, verbose_name='Código de punto de venta'),
        ),
    ]
