# Generated by Django 5.0.1 on 2024-02-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0024_empresa_codigoestablecimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigoEstablecimiento',
            field=models.CharField(blank=True, db_column='codigoEstablecimiento', default='0000', max_length=4, null=True, verbose_name='Código de establecimiento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigoPuntoVenta',
            field=models.CharField(blank=True, db_column='codigoPuntoVenta', default='0000', max_length=4, null=True, verbose_name='Código de punto de venta'),
        ),
    ]
