# Generated by Django 5.0.1 on 2024-02-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0025_alter_empresa_codigoestablecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsistema',
            name='url_consulta_produccion',
            field=models.URLField(db_column='URLConsultaProduccion', default='', max_length=100, verbose_name='URL para consulta DTE producción'),
        ),
        migrations.AddField(
            model_name='urlsistema',
            name='url_consulta_prueba',
            field=models.URLField(db_column='URLConsultaPruebas', default='', max_length=100, verbose_name='URL para consulta DTE pruebas'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_anulacion_produccion',
            field=models.URLField(db_column='URLAnulacionProduccion', default='', max_length=100, verbose_name='URL para anulación DTE producción'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_anulacion_prueba',
            field=models.URLField(db_column='URLAnulacionPruebas', default='', max_length=100, verbose_name='URL para anulación DTE pruebas'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_auth_produccion',
            field=models.URLField(db_column='URLAuthProduccion', default='', max_length=100, verbose_name='URL autenticación producción'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_auth_prueba',
            field=models.URLField(db_column='URLAuthPruebas', default='', max_length=100, verbose_name='URL autenticación pruebas'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_contingencia_produccion',
            field=models.URLField(db_column='URLContingenciaProduccion', default='', max_length=100, verbose_name='URL para contingencia DTE producción'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_contingencia_prueba',
            field=models.URLField(db_column='URLContingenciaPruebas', default='', max_length=100, verbose_name='URL para contingencia DTE pruebas'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_envio_produccion',
            field=models.URLField(db_column='URLEnvioProduccion', default='', max_length=100, verbose_name='URL para envío DTE producción'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_envio_prueba',
            field=models.URLField(db_column='URLEnvioPruebas', default='', max_length=100, verbose_name='URL para envío DTE pruebas'),
        ),
        migrations.AlterField(
            model_name='urlsistema',
            name='url_firmado',
            field=models.URLField(db_column='URLFirmado', default='', max_length=100, verbose_name='Url para firmar DTE'),
        ),
    ]
