# Generated by Django 5.0.1 on 2024-02-26 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0026_urlsistema_url_consulta_produccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlsistema',
            old_name='url_firmado',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_absoluta_static',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_almacen_archivos',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_anulacion_produccion',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_anulacion_prueba',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_auth_produccion',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_auth_prueba',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_consulta_produccion',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_consulta_prueba',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_contingencia_produccion',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_contingencia_prueba',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_envio_produccion',
        ),
        migrations.RemoveField(
            model_name='urlsistema',
            name='url_envio_prueba',
        ),
        migrations.AddField(
            model_name='urlsistema',
            name='ambiente',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to='dte.ambientedestino', verbose_name='Ambiente'),
        ),
        migrations.AddField(
            model_name='urlsistema',
            name='tipo',
            field=models.CharField(db_column='tipo', default='', max_length=20, verbose_name='Tipo'),
        ),
    ]
