# Generated by Django 5.0.1 on 2024-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0028_remove_configseg_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='passwordAPI',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='passwordPri',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='token',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuarioMH',
        ),
        migrations.AddField(
            model_name='empresa',
            name='passwordAPI',
            field=models.CharField(db_column='PasswordAPI', default='', max_length=50, verbose_name='Clave acceso API (generar token MH)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='passwordPri',
            field=models.CharField(db_column='PasswordPri', default='', max_length=50, verbose_name='Clave privada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token',
            field=models.TextField(db_column='Token', default='', max_length=500, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuarioMH',
            field=models.CharField(db_column='UsuarioMH', default='', max_length=50, verbose_name='Usuario en Ministerio de Hacienda'),
        ),
    ]
