# Generated by Django 5.0.1 on 2024-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0029_remove_cliente_passwordapi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccionComplemento',
            field=models.TextField(blank=True, db_column='Direccion', max_length=200, null=True),
        ),
    ]
