# Generated by Django 5.0.1 on 2024-02-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0030_alter_empresa_direccioncomplemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='actividadEconomica',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.actividadeconomica', verbose_name='Actividad económica'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccionComplemento',
            field=models.TextField(blank=True, db_column='Direccion', max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipoContribuyente',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontribuyente', verbose_name='Tipo de contribuyente'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipoPersona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipopersona', verbose_name='Tipo de persona'),
        ),
    ]
