# Generated by Django 5.0.1 on 2024-02-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0032_empresa_tipoestablecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='codigoDetalle',
            field=models.CharField(blank=True, db_column='CodigoDetalle', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipoEstablecimiento',
            field=models.ForeignKey(default='02', on_delete=django.db.models.deletion.CASCADE, to='dte.tipoestablecimiento', verbose_name='Tipo de establecimiento'),
        ),
    ]
