# Generated by Django 5.0.1 on 2024-02-27 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0033_alter_dteclientedetalle_codigodetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTEClienteDetalleTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', default='', max_length=100, verbose_name='Descripción del tributo')),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, default=0, max_digits=11)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.tributoresumen')),
                ('codigoDetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.dteclientedetalle')),
            ],
            options={
                'verbose_name': 'DTE Detalle tributo',
                'verbose_name_plural': 'DTE Detalle tributos',
                'db_table': 'DTEDetalleTributo',
            },
        ),
    ]
