# Generated by Django 5.0.1 on 2024-02-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0034_dteclientedetalletributo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dteclientedetalletributo',
            table='dte_dteclientedetalletributo',
        ),
    ]
