# Generated by Django 5.0.1 on 2024-02-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0035_alter_dteclientedetalletributo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dteclientedetalletributo',
            table=None,
        ),
    ]
