# Generated by Django 5.0.1 on 2024-03-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0037_cliente_nrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='uniMedida',
            field=models.ForeignKey(db_column='uniMedida_id', default='59', on_delete=django.db.models.deletion.CASCADE, to='dte.unidadmedida', verbose_name='Unidad de medida'),
        ),
    ]
