# Generated by Django 5.0.1 on 2024-03-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0038_alter_dteclientedetalle_unimedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(blank=True, db_column='Correo', max_length=200, null=True, verbose_name='Correo'),
        ),
    ]
