# Generated by Django 5.0.1 on 2024-03-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0040_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, db_column='Precio', decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Precio'),
        ),
    ]
