# Generated by Django 5.0.1 on 2024-03-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0041_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidadMedida',
            field=models.ForeignKey(default=59, on_delete=django.db.models.deletion.CASCADE, to='dte.unidadmedida', verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidadMinima',
            field=models.DecimalField(blank=True, db_column='CantidadMinima', decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Cantidad mínima'),
        ),
    ]
