# Generated by Django 5.0.1 on 2024-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0042_producto_unidadmedida_alter_producto_cantidadminima'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencia',
            field=models.DecimalField(blank=True, db_column='Existencia', decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Existencia'),
        ),
    ]
