# Generated by Django 5.0.1 on 2024-03-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0043_producto_existencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('nombre',)},
        ),
    ]
