# Generated by Django 5.0.1 on 2024-03-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0044_alter_producto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(db_column='dodigo', default='001', max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(blank=True, db_column='nombre', default='N/A', max_length=200, verbose_name='Nombre'),
        ),
    ]
