# Generated by Django 5.0.1 on 2024-03-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0045_alter_municipio_codigo_alter_municipio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(db_column='codigo', default='001', max_length=50, verbose_name='Código'),
        ),
    ]
