# Generated by Django 5.0.3 on 2024-03-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0047_empresa_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configseg',
            old_name='clave_correo',
            new_name='claveCorreo',
        ),
        migrations.RenameField(
            model_name='configseg',
            old_name='usuario_correo',
            new_name='usuarioCorreo',
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='observaciones',
            field=models.CharField(blank=True, db_column='Observaciones', default='', max_length=3000, null=True, verbose_name='Observaciones'),
        ),
    ]
