# Generated by Django 5.0.3 on 2024-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0049_rename_configseg_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='blobUrl',
            field=models.CharField(db_column='blobUrl', default='', max_length=500, verbose_name='Blob url'),
        ),
    ]
