# Generated by Django 5.0.3 on 2024-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0050_configuracion_bloburl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='EnableSsl',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='enableSsl',
            field=models.BooleanField(default=True, verbose_name='Utiliza SSL'),
        ),
    ]
