# Generated by Django 5.0.3 on 2024-03-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0052_remove_configuracion_puerto_smtp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuración'},
        ),
    ]
