# Generated by Django 5.0.3 on 2024-03-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0053_alter_configuracion_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
