# Generated by Django 5.0.3 on 2024-03-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0054_delete_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioCorreo', models.EmailField(default='none@usuario.com', max_length=500, verbose_name='Usuario de correo')),
                ('claveCorreo', models.CharField(default='', max_length=500, verbose_name='Clave de correo')),
                ('servidorSmtp', models.CharField(default='', max_length=500, verbose_name='Servidor SMTP')),
                ('puertoSmtp', models.IntegerField(default=587, verbose_name='Puerto SMTP')),
                ('enableSsl', models.BooleanField(default=True, verbose_name='Utiliza SSL')),
                ('blobUrl', models.CharField(default='', max_length=500, verbose_name='Blob url')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
