# Generated by Django 5.0.3 on 2024-03-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0055_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='blobCadenaConexion',
            field=models.CharField(default='', max_length=500, verbose_name='Blob cadena de conexión'),
        ),
    ]
