# Generated by Django 5.0.3 on 2024-03-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0056_configuracion_blobcadenaconexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='blobContenedor',
            field=models.CharField(default='', max_length=50, verbose_name='Blob url'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='blobCadenaConexion',
            field=models.TextField(default='', max_length=500, verbose_name='Blob cadena de conexión'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='blobUrl',
            field=models.CharField(default='', max_length=100, verbose_name='Blob url'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='claveCorreo',
            field=models.CharField(default='', max_length=50, verbose_name='Clave de correo'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='servidorSmtp',
            field=models.CharField(default='', max_length=50, verbose_name='Servidor SMTP'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='usuarioCorreo',
            field=models.EmailField(default='none@usuario.com', max_length=50, verbose_name='Usuario de correo'),
        ),
    ]
