# Generated by Django 5.0.3 on 2024-04-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0057_configuracion_blobcontenedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtecliente',
            name='recintoFiscal',
            field=models.ForeignKey(blank=True, default='01', null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.recintofiscal', verbose_name='Recinto fiscal'),
        ),
        migrations.AddField(
            model_name='dtecliente',
            name='tipoItemExpor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tipoitem', verbose_name='Tipo ítem de exportación'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='blobContenedor',
            field=models.CharField(default='', max_length=50, verbose_name='Blob contenedor'),
        ),
    ]
