# Generated by Django 5.0.3 on 2024-04-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0058_dtecliente_recintofiscal_dtecliente_tipoitemexpor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtecliente',
            name='recintoFiscal',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.recintofiscal', verbose_name='Recinto fiscal'),
        ),
        migrations.AlterField(
            model_name='regimen',
            name='nombre',
            field=models.CharField(blank=True, db_column='Nombre', default='N/A', max_length=300),
        ),
    ]
