# Generated by Django 5.0.3 on 2024-04-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0061_rename_incoterm_incoterms_alter_incoterms_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtecliente',
            name='incoterms',
            field=models.ForeignKey(blank=True, default='02', null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.incoterms', verbose_name='Incoterms'),
        ),
    ]
