# Generated by Django 5.0.3 on 2024-04-02 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0062_dtecliente_incoterms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ('nombre',), 'verbose_name': 'País', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AddField(
            model_name='dtecliente',
            name='totalCompra',
            field=models.DecimalField(blank=True, db_column='TotalCompra', decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total compra'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='incoterms',
            field=models.ForeignKey(blank=True, default='01', null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.incoterms', verbose_name='Incoterms'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='recintoFiscal',
            field=models.ForeignKey(blank=True, default='02', null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.recintofiscal', verbose_name='Recinto fiscal'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='regimen',
            field=models.ForeignKey(blank=True, default='EX-1.1000.000', null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.regimen', verbose_name='Regimen'),
        ),
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='tipoItem',
            field=models.ForeignKey(db_column='tipoItem_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipoitem', verbose_name='Tipo de ítem'),
        ),
    ]
