# Generated by Django 5.0.3 on 2024-04-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0064_rename_codigodetalle_dteclientedetalletributo_codigodetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dteclientedetalletributo',
            old_name='codigodetalle',
            new_name='codigoDetalle',
        ),
    ]
