# Generated by Django 5.0.3 on 2024-04-06 10:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0065_rename_codigodetalle_dteclientedetalletributo_codigodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTEInvalidacion',
            fields=[
                ('codigoGeneracion', models.CharField(default='', max_length=36, primary_key=True, serialize=False, verbose_name='Código de generación')),
                ('codigoDte', models.CharField(default='', max_length=36, verbose_name='Código DTE a anular')),
                ('fechaEmimision', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de emisión')),
                ('emisor', models.ForeignKey(default='A4BCBC83-4C59-4A3F-9C25-807D83AD0837', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
                ('receptor', models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.cliente')),
                ('tipoDte', models.ForeignKey(db_column='TipoDTE', default='', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo DTE')),
                ('tipoInvalidacion', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dte.tipoinvalidacion', verbose_name='Tipo de anulación')),
            ],
            options={
                'verbose_name': 'Invalidación DTE',
                'verbose_name_plural': "Invalidaciones de DTE's",
            },
        ),
    ]
