# Generated by Django 5.0.3 on 2024-04-07 18:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0068_rename_fechaemimision_dteinvalidacion_fechaemision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteinvalidacion',
            name='selloRecepcion',
            field=models.CharField(default='', max_length=50, verbose_name='Sello de recepción'),
        ),
        migrations.CreateModel(
            name='DTEContingencia',
            fields=[
                ('codigoGeneracion', models.CharField(default='', max_length=36, primary_key=True, serialize=False, verbose_name='Código de generación')),
                ('version', models.IntegerField(db_column='Version', default=3, verbose_name='Versión JSON')),
                ('fTransmision', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de transmisión')),
                ('finicio', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha inicio de contingencia')),
                ('fFinal', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha fin de contingencia')),
                ('docfirmado', models.TextField(blank=True, db_column='DocFirmado', null=True, verbose_name='Documento firmado')),
                ('selloRecepcion', models.CharField(default='', max_length=50, verbose_name='Sello de recepción')),
                ('ambiente', models.ForeignKey(db_column='Ambiente', default='00', on_delete=django.db.models.deletion.CASCADE, to='dte.ambientedestino', verbose_name='Ambiente de trabajo')),
                ('emisor', models.ForeignKey(default='A4BCBC83-4C59-4A3F-9C25-807D83AD0837', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa')),
                ('tipoContingencia', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontingencia', verbose_name='Tipo de contingencia')),
            ],
            options={
                'verbose_name': 'Contingencia DTE',
                'verbose_name_plural': "Contingencia de DTE's",
            },
        ),
    ]
