# Generated by Django 5.0.3 on 2024-04-07 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0069_alter_dteinvalidacion_sellorecepcion_dtecontingencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTEContingenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoGeneracionDTE', models.CharField(default='', max_length=36, verbose_name='Codigo DTE a reportar')),
                ('dteContingencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.dtecontingencia', verbose_name='Dte')),
            ],
            options={
                'verbose_name': 'Detalle contingencia DTE',
                'verbose_name_plural': "Detalles contingencia de DTE's",
            },
        ),
    ]
