# Generated by Django 5.0.3 on 2024-04-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0071_dteproveedor_dteproveedordetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtecontingencia',
            old_name='finicio',
            new_name='fInicio',
        ),
    ]
