# Generated by Django 5.0.3 on 2024-04-10 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0072_rename_finicio_dtecontingencia_finicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtecontingencia',
            name='tipoDte',
            field=models.ForeignKey(default='03', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo DTE'),
        ),
        migrations.AddField(
            model_name='dtecontingenciadetalle',
            name='tipoDte',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo DTE'),
        ),
    ]
