# Generated by Django 5.0.3 on 2024-04-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0073_dtecontingencia_tipodte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtecontingencia',
            name='tipoDte',
            field=models.ForeignKey(default='03', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumentocontingencia', verbose_name='Tipo DTE'),
        ),
    ]
