# Generated by Django 5.0.3 on 2024-04-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0080_dtecontingenciadetalle_tipodte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtecontingencia',
            name='docfirmado',
            field=models.TextField(blank=True, null=True, verbose_name='Documento firmado'),
        ),
        migrations.AlterField(
            model_name='dtecontingencia',
            name='tipoContingencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontingencia', verbose_name='Tipo de contingencia'),
        ),
        migrations.AlterField(
            model_name='dtecontingencia',
            name='version',
            field=models.IntegerField(default=3, verbose_name='Versión JSON'),
        ),
    ]
