# Generated by Django 5.0.3 on 2024-04-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0081_alter_dtecontingencia_docfirmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dteinvalidacion',
            name='numeroDocumento',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Número de documento'),
        ),
    ]
