# Generated by Django 5.0.3 on 2024-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0083_alter_dtecontingenciadetalle_codigogeneraciondte'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtecontingencia',
            name='numeroControl',
            field=models.CharField(blank=True, default='', max_length=31, null=True, verbose_name='Número de control'),
        ),
    ]
