# Generated by Django 5.0.3 on 2024-04-13 17:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0085_alter_dtecliente_fecemi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtecliente',
            name='ambiente',
            field=models.ForeignKey(default='00', on_delete=django.db.models.deletion.CASCADE, to='dte.ambientedestino', verbose_name='Ambiente de trabajo'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='codigoGeneracion',
            field=models.CharField(default='', max_length=36, primary_key=True, serialize=False, verbose_name='Código de generación'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='descuExenta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Descuento exentas'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='descuGravada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Descuento gravadas'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='descuNoSuj',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Descuento no sujetas'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='docfirmado',
            field=models.TextField(blank=True, null=True, verbose_name='Documento firmado'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='estadoPago',
            field=models.BooleanField(blank=True, default=True, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='fechaPago',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='ivaPerci1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='IVA rercibido'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='ivaRete1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='IVA retenido'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='montoTotalOperacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Monto total de operación'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='motivoContin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Motivo de contingencia'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='numPagoElectronico',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de pago electrónico'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='numeroControl',
            field=models.CharField(blank=True, default='', max_length=31, null=True, verbose_name='Número de control'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=3000, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='pagos',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='placaVehiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa del vehículo'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='porcentajeDescuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Porcentaje descuento'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='reteRenta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Retención de renta'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='saldoFavor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Saldo a favor'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Sub total'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='subTotalVentas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Sub-total ventas'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='tipoDte',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo DTE'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='totalCompra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total compra'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='totalDescu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total descuento'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='totalExenta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total exentas'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='totalGravada',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total gravadas'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='totalLetras',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Total en letras'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='totalNoGravado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total no gravado'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='totalNoSuj',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total no sujetas'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='totalPagar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total a pagar'),
        ),
    ]
