# Generated by Django 5.0.3 on 2024-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0086_alter_dtecliente_ambiente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='tipoDocumentoCliente',
            new_name='tipoDocumentoProveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nrc',
            field=models.CharField(blank=True, db_column='NRC', default='', max_length=10, null=True, verbose_name='NRC'),
        ),
    ]
