# Generated by Django 5.0.3 on 2024-05-23 16:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0088_userprofile_codigoestablecimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtesempresa',
            options={'ordering': ('empresa',), 'verbose_name': 'Dte autorizado por empresa', 'verbose_name_plural': "Dte's autorizados por empresa"},
        ),
        migrations.AddField(
            model_name='empresa',
            name='fechaToken',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora del token'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='incoterms',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.incoterms', verbose_name='Incoterms'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='recintoFiscal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.recintofiscal', verbose_name='Recinto fiscal'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='regimen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.regimen', verbose_name='Regimen'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='tipoItemExpor',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.tipoitem', verbose_name='Tipo ítem de exportación'),
        ),
    ]
