# Generated by Django 5.0.3 on 2024-05-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0089_alter_dtesempresa_options_empresa_fechatoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, db_column='Cantidad', decimal_places=3, default=1, max_digits=11, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='actividadEconomica',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.actividadeconomica', verbose_name='Actividad económica'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccionComplemento',
            field=models.CharField(blank=True, db_column='Direccion', max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipoContribuyente',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.tipocontribuyente', verbose_name='Tipo de contribuyente'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipoPersona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipopersona', verbose_name='Tipo de persona'),
        ),
    ]
