# Generated by Django 5.0.3 on 2024-05-24 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0090_alter_dteclientedetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dteproveedor',
            name='condicionOperacion',
            field=models.ForeignKey(db_column='CondicionOperacion', default='2', on_delete=django.db.models.deletion.CASCADE, to='dte.condicionoperacion', verbose_name='Condición de la operación'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='descu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='estadoPago',
            field=models.BooleanField(blank=True, default=True, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='ivaRete1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='IVA retenido'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=3000, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='pagos',
            field=models.IntegerField(blank=True, default=1, verbose_name='Pagos'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='reteRenta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Retención de renta'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Sub total'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='totalCompra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total compra'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='totalDescu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total descuento'),
        ),
        migrations.AddField(
            model_name='dteproveedor',
            name='totalPagar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='Total a pagar'),
        ),
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=11, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='descripcion',
            field=models.CharField(default='', max_length=1000, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='montoDescu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Monto de descuento'),
        ),
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='precioUni',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Precio unitario'),
        ),
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='tipoItem',
            field=models.ForeignKey(db_column='tipoItem_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='dte.tipoitem', verbose_name='Tipo de ítem'),
        ),
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='uniMedida',
            field=models.ForeignKey(db_column='uniMedida_id', default='59', on_delete=django.db.models.deletion.CASCADE, to='dte.unidadmedida', verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='dteproveedor',
            name='tipoMoneda',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, to='dte.moneda', verbose_name='Tipo moneda'),
        ),
    ]
