# Generated by Django 5.0.3 on 2024-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0091_dteproveedor_condicionoperacion_dteproveedor_descu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dteproveedordetalle',
            name='complemento1',
            field=models.CharField(blank=True, db_column='Complemento1', default='', max_length=3000, null=True, verbose_name='Complemento 1'),
        ),
    ]
