# Generated by Django 5.0.3 on 2024-05-27 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0092_dteproveedordetalle_complemento1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dteclientedetalletributo',
            options={'verbose_name': 'DTE Cliente Detalle tributo', 'verbose_name_plural': 'DTE Cliente Detalle tributos'},
        ),
        migrations.CreateModel(
            name='DTEProveedorDetalleTributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=100, verbose_name='Descripción del tributo')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.tributoresumen')),
                ('codigoDetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dte.dteproveedordetalle')),
            ],
            options={
                'verbose_name': 'DTE Proveedor Detalle tributo',
                'verbose_name_plural': 'DTE Proveedor Detalle tributos',
            },
        ),
    ]
