# Generated by Django 5.0.3 on 2024-05-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0093_alter_dteclientedetalletributo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtecontingencia',
            options={'verbose_name': 'DTE de contingencia', 'verbose_name_plural': "DTE's de contingencia"},
        ),
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='tipoItem',
            field=models.ForeignKey(db_column='tipoItem_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='dte.tipoitem', verbose_name='Tipo de ítem'),
        ),
    ]
