# Generated by Django 5.0.3 on 2024-06-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0094_alter_dtecontingencia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtecontingencia',
            options={'ordering': ('-fTransmision',), 'verbose_name': 'DTE de contingencia', 'verbose_name_plural': "DTE's de contingencia"},
        ),
    ]
