# Generated by Django 5.0.3 on 2024-06-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0098_empresa_correoclave_empresa_correoenablessl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correoClave',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Clave de correo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoEnableSsl',
            field=models.BooleanField(default=True, null=True, verbose_name='Utiliza SSL'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoPuertoSmtp',
            field=models.IntegerField(default=587, null=True, verbose_name='Puerto SMTP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoServidorSmtp',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Servidor SMTP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoUsuario',
            field=models.EmailField(default='usuario@empresa.com', max_length=50, null=True, verbose_name='Usuario de correo'),
        ),
    ]
