# Generated by Django 5.0.3 on 2024-06-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0099_alter_empresa_correoclave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='correoClave',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Clave de correo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoEnableSsl',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Utiliza SSL'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoPuertoSmtp',
            field=models.IntegerField(blank=True, default=587, null=True, verbose_name='Puerto SMTP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoServidorSmtp',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Servidor SMTP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correoUsuario',
            field=models.EmailField(blank=True, default='', max_length=50, null=True, verbose_name='Usuario de correo'),
        ),
    ]
