# Generated by Django 5.0.3 on 2024-06-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0100_alter_empresa_correoclave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='agenteRetencion',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sí'),
        ),
    ]
