# Generated by Django 5.0.3 on 2024-06-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0101_cliente_agenteretencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAccionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='agenteRetencion',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cliente es agente de retención'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(db_column='Correo', default='', max_length=200, verbose_name='Correo 1'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='ivaPerci1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18, null=True, verbose_name='IVA percibido'),
        ),
    ]
