# Generated by Django 5.0.3 on 2024-06-21 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0104_alter_tipoaccionusuario_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaccionusuario',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='bitacoraacciondtec',
            name='tipoDte',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo DTE'),
        ),
    ]
