# Generated by Django 5.0.3 on 2024-06-21 00:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0106_bitacoraacciondtep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAccionDte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte', models.CharField(blank=True, default='', max_length=36, null=True, verbose_name='´DTE')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('accion', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dte.tipoaccionusuario', verbose_name='Acción')),
                ('tipoDte', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='dte.tipodocumento', verbose_name='Tipo DTE')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='BitacoraAccionDteC',
        ),
    ]
