# Generated by Django 5.0.3 on 2024-06-21 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0107_bitacoraacciondte_delete_bitacoraacciondtec'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraacciondte',
            name='empresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dte.empresa', verbose_name='Empresa'),
        ),
    ]
