# Generated by Django 5.0.3 on 2024-06-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0109_alter_bitacoraacciondte_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dteinvalidacion',
            name='receptor_tmp',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
    ]
