# Generated by Django 5.0.3 on 2024-06-22 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0110_dteinvalidacion_receptor_tmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteinvalidacion',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.cliente'),
        ),
    ]
