# Generated by Django 5.0.3 on 2024-06-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0112_cliente_correo2_cliente_correo3_cliente_diascredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo2',
            field=models.CharField(default='', max_length=100, verbose_name='Correo 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo3',
            field=models.CharField(default='', max_length=100, verbose_name='Correo 3'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='diasCredito',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Días crédito'),
        ),
    ]
