# Generated by Django 5.0.3 on 2024-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0113_alter_cliente_correo2_alter_cliente_correo3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo2',
            field=models.CharField(default='', max_length=200, verbose_name='Correo 2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo3',
            field=models.CharField(default='', max_length=200, verbose_name='Correo 3'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='diasCredito',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Días crédito'),
        ),
    ]
