# Generated by Django 5.0.3 on 2024-06-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0114_alter_cliente_correo2_alter_cliente_correo3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtecliente',
            name='diasCredito',
            field=models.IntegerField(blank=True, default=30, null=True, verbose_name='Días crédito'),
        ),
    ]
