# Generated by Django 5.0.3 on 2024-06-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0115_dtecliente_diascredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='departamento',
            field=models.ForeignKey(blank=True, default='001', null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(blank=True, default='001', null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.municipio', verbose_name='Municipio'),
        ),
    ]
