# Generated by Django 5.0.3 on 2024-07-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0117_alter_tituloremision_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='precioUni',
            field=models.DecimalField(db_column='PrecioUnitario', decimal_places=4, default=0, max_digits=11, verbose_name='Precio unitario'),
        ),
    ]
