# Generated by Django 5.0.3 on 2024-07-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0119_alter_dtecliente_totalgravada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtecliente',
            name='ivaPerci1',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True, verbose_name='IVA percibido'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='ivaRete1',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True, verbose_name='IVA retenido'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='montoTotalOperacion',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True, verbose_name='Monto total de operación'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True, verbose_name='Sub total'),
        ),
        migrations.AlterField(
            model_name='dtecliente',
            name='subTotalVentas',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=18, null=True, verbose_name='Sub-total ventas'),
        ),
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='iva',
            field=models.DecimalField(db_column='IVA', decimal_places=4, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='ivaPercibido',
            field=models.DecimalField(db_column='IVAPercibido', decimal_places=4, default=0, max_digits=11, verbose_name='IVA Percibido'),
        ),
        migrations.AlterField(
            model_name='dteclientedetalle',
            name='ivaRetenido',
            field=models.DecimalField(db_column='IVARetenido', decimal_places=4, default=0, max_digits=11, verbose_name='IVA retenido'),
        ),
    ]
