# Generated by Django 5.0.3 on 2024-07-14 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0122_dtecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='dteclientedetalle',
            name='fechaCreacion',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de emisión'),
        ),
    ]
