# Generated by Django 5.0.3 on 2024-07-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0123_dteclientedetalle_fechacreacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dteclientedetalle',
            options={'ordering': ('fechaCreacion',), 'verbose_name': 'DTE cliente detalle', 'verbose_name_plural': "DTE's cliente detalles"},
        ),
    ]
