# Generated by Django 5.0.3 on 2024-07-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0125_alter_dtecliente_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dteproveedor',
            name='receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dte.proveedor'),
        ),
    ]
