# Generated by Django 5.0.3 on 2024-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0126_alter_dteproveedor_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, db_column='Telefono', max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
